# Generated by Django 6.0.4 on 2026-04-30 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStreamlinePreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='streamline_preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hidden_activity_types', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user streamline preference',
                'verbose_name_plural': 'user streamline preferences',
            },
        ),
    ]
