# Generated by Django 6.0.4 on 2026-05-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userstreamlinepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_locale',
            field=models.CharField(blank=True, default='', help_text="BCP 47 locale tag for number/currency formatting (e.g. 'cs-CZ', 'en-US'). When empty the workspace default locale is used.", max_length=10),
        ),
    ]
