# Generated by Django 6.0.4 on 2026-05-04 04:43

import firms.models
import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A human-readable label for this token.', max_length=100)),
                ('prefix', models.CharField(help_text='First few characters of the token, shown in listings.', max_length=8)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw token value.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API token',
                'verbose_name_plural': 'API tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=20)),
                ('subscription_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='firm_logos/')),
                ('primary_color', models.CharField(blank=True, default='#dc2626', max_length=7)),
                ('default_currency', models.CharField(default='CZK', help_text='ISO 4217 currency code used as the reporting currency for this workspace.', max_length=3)),
                ('number_locale', models.CharField(default='cs-CZ', help_text="BCP 47 locale tag controlling number/currency formatting (e.g. 'cs-CZ', 'en-US').", max_length=10)),
                ('exchange_rate_mode', models.CharField(choices=[('auto', 'Automatic (ECB)'), ('manual', 'Manual rates')], default='auto', help_text='How exchange rates are sourced for this workspace.', max_length=10)),
            ],
            options={
                'verbose_name': 'firm',
                'verbose_name_plural': 'firms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FirmExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ecb', 'ECB Auto')], default='manual', max_length=10)),
                ('valid_from', models.DateField(help_text='Rate is effective from this date (inclusive).')),
                ('valid_to', models.DateField(blank=True, help_text='Rate is effective until this date (inclusive). NULL = currently active.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, help_text='Optional note visible to team members.', max_length=255)),
            ],
            options={
                'verbose_name': 'firm exchange rate',
                'verbose_name_plural': 'firm exchange rates',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('worker', 'Worker')], default='worker', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=firms.models._default_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('worker', 'Worker')], default='worker', max_length=20)),
                ('weekly_digest_enabled', models.BooleanField(default=True, help_text='Receive a weekly email digest with pipeline summary for this workspace.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
                'ordering': ['firm', 'role'],
            },
        ),
        migrations.CreateModel(
            name='PluginConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin_name', models.CharField(help_text="Matches LeadLabPlugin.manifest['name'].", max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text="Plugin-specific configuration values (validated by plugin's config_schema).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plugin config',
                'verbose_name_plural': 'plugin configs',
                'ordering': ['plugin_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='EUR', max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('date', models.DateField()),
                ('source', models.CharField(default='ecb', max_length=20)),
            ],
            options={
                'verbose_name': 'system exchange rate',
                'verbose_name_plural': 'system exchange rates',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'webhook delivery',
                'verbose_name_plural': 'webhook deliveries',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='The URL that will receive POST requests.', max_length=500)),
                ('secret', models.CharField(default=secrets.token_hex, help_text='HMAC signing secret — sent as X-LeadLab-Signature.', max_length=64)),
                ('events', models.JSONField(default=list, help_text="List of event names to subscribe to, e.g. ['record.created', 'activity.created']. Empty list means all events.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'webhook endpoint',
                'verbose_name_plural': 'webhook endpoints',
                'ordering': ['-created_at'],
            },
        ),
    ]
