# Generated by Django 6.0.4 on 2026-05-04 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('firms', '0002_invitation_model'),
        ('firms', '0003_apitoken_webhook'),
        ('firms', '0004_add_weekly_digest_enabled'),
        ('firms', '0005_firm_branding'),
        ('firms', '0006_plugin_config'),
        ('firms', '0007_alter_pluginconfig_config'),
        ('firms', '0008_firm_fakturoid'),
        ('firms', '0009_remove_firm_fakturoid'),
        ('firms', '0010_firm_currency_settings'),
        ('firms', '0011_add_exchange_rate_models'),
    ]

    dependencies = [
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='firmexchangerate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this rate (NULL for system/ECB rates).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firmexchangerate',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pluginconfig',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_configs', to='firms.firm'),
        ),
        migrations.AddIndex(
            model_name='systemexchangerate',
            index=models.Index(fields=['quote_currency', '-date'], name='firms_syste_quote_c_c26040_idx'),
        ),
        migrations.AddIndex(
            model_name='systemexchangerate',
            index=models.Index(fields=['base_currency', '-date'], name='firms_syste_base_cu_05de4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='systemexchangerate',
            unique_together={('base_currency', 'quote_currency', 'date')},
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='firms.webhookendpoint'),
        ),
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['firm', 'user'], name='firms_apito_firm_id_555339_idx'),
        ),
        migrations.AddIndex(
            model_name='firmexchangerate',
            index=models.Index(fields=['firm', 'from_currency', 'to_currency', '-valid_from'], name='firms_firme_firm_id_e23100_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('email', 'firm')},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'firm')},
        ),
        migrations.AlterUniqueTogether(
            name='pluginconfig',
            unique_together={('firm', 'plugin_name')},
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', '-delivered_at'], name='firms_webho_endpoin_0ee295_idx'),
        ),
    ]
