# Generated by Django 6.0.4 on 2026-04-25 22:29

import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0002_invitation_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='The URL that will receive POST requests.', max_length=500)),
                ('secret', models.CharField(default=secrets.token_hex, help_text='HMAC signing secret — sent as X-LeadLab-Signature.', max_length=64)),
                ('events', models.JSONField(default=list, help_text="List of event names to subscribe to, e.g. ['lead.created', 'activity.created']. Empty list means all events.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='firms.firm')),
            ],
            options={
                'verbose_name': 'webhook endpoint',
                'verbose_name_plural': 'webhook endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A human-readable label for this token.', max_length=100)),
                ('prefix', models.CharField(help_text='First few characters of the token, shown in listings.', max_length=8)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw token value.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='firms.firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API token',
                'verbose_name_plural': 'API tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['firm', 'user'], name='firms_apito_firm_id_555339_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='firms.webhookendpoint')),
            ],
            options={
                'verbose_name': 'webhook delivery',
                'verbose_name_plural': 'webhook deliveries',
                'ordering': ['-delivered_at'],
                'indexes': [models.Index(fields=['endpoint', '-delivered_at'], name='firms_webho_endpoin_0ee295_idx')],
            },
        ),
    ]
