# Generated by Django 6.0.4 on 2026-04-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0003_apitoken_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='weekly_digest_enabled',
            field=models.BooleanField(default=True, help_text='Receive a weekly email digest with pipeline summary for this workspace.'),
        ),
    ]
