# Generated by Django 6.0.5 on 2026-05-06 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0005_permission_audit_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='permissionauditlog',
            new_name='firms_permi_firm_id_0718ca_idx',
            old_name='firms_permi_firm_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionauditlog',
            new_name='firms_permi_actor_i_fa7a63_idx',
            old_name='firms_permi_actor_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionauditlog',
            new_name='firms_permi_target__68dd6f_idx',
            old_name='firms_permi_tgt_type_id_idx',
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_default_scope',
            field=models.CharField(blank=True, default='', help_text='Default scope to apply to the Membership on accept (own/team/category/all).', max_length=20),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_role_codes',
            field=models.JSONField(blank=True, default=list, help_text='List of Role.code strings to assign to the Membership on accept.'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_team',
            field=models.ForeignKey(blank=True, help_text='Team to assign the invitee to on accept.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_invitations', to='firms.team'),
        ),
    ]
