# Generated by Django 6.0.4 on 2026-04-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0006_plugin_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginconfig',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text="Plugin-specific configuration values (validated by plugin's config_schema)."),
        ),
    ]
