# Generated by Django 6.0.4 on 2026-05-03 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0010_firm_currency_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='EUR', max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('date', models.DateField()),
                ('source', models.CharField(default='ecb', max_length=20)),
            ],
            options={
                'verbose_name': 'system exchange rate',
                'verbose_name_plural': 'system exchange rates',
                'indexes': [models.Index(fields=['quote_currency', '-date'], name='firms_syste_quote_c_c26040_idx'), models.Index(fields=['base_currency', '-date'], name='firms_syste_base_cu_05de4f_idx')],
                'unique_together': {('base_currency', 'quote_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FirmExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ecb', 'ECB Auto')], default='manual', max_length=10)),
                ('valid_from', models.DateField(help_text='Rate is effective from this date (inclusive).')),
                ('valid_to', models.DateField(blank=True, help_text='Rate is effective until this date (inclusive). NULL = currently active.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, help_text='Optional note visible to team members.', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this rate (NULL for system/ECB rates).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='firms.firm')),
            ],
            options={
                'verbose_name': 'firm exchange rate',
                'verbose_name_plural': 'firm exchange rates',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['firm', 'from_currency', 'to_currency', '-valid_from'], name='firms_firme_firm_id_e23100_idx')],
            },
        ),
    ]
