# Generated by Django 6.0.5 on 2026-05-06 19:43

import django.db.models.deletion
import firms.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0012_membership_expiry_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionauditlog',
            name='action',
            field=models.CharField(choices=[('role.created', 'Role created'), ('role.updated', 'Role updated'), ('role.deleted', 'Role deleted'), ('membership.created', 'Membership created'), ('membership.updated', 'Membership updated'), ('membership.deleted', 'Membership deleted'), ('membership.expired', 'Membership expired'), ('category_grant.created', 'CategoryGrant created'), ('category_grant.deleted', 'CategoryGrant deleted'), ('record_grant.created', 'RecordGrant created'), ('record_grant.deleted', 'RecordGrant deleted'), ('ownership.transfer_initiated', 'Ownership transfer initiated'), ('ownership.transfer_confirmed', 'Ownership transfer confirmed'), ('ownership.transfer_cancelled', 'Ownership transfer cancelled')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='OwnershipTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Secret token sent to the new owner to confirm the transfer.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=firms.models._default_transfer_expiry, help_text='The transfer confirmation link expires after this timestamp.')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Set when the new owner confirms the transfer.', null=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_transfers', to='firms.firm')),
                ('from_user', models.ForeignKey(help_text='The current Owner who initiated the transfer.', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(help_text='The user who will become the new Owner.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ownership transfer',
                'verbose_name_plural': 'ownership transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
