# Generated by Django 6.0.4 on 2026-04-25 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of free-form string tags for quick filtering.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value pairs for custom fields.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['last_name', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('canceled', 'Canceled')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('referral', 'Referral'), ('cold_call', 'Cold Call'), ('social', 'Social'), ('other', 'Other')], default='web', max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated deal value.', max_digits=14, null=True)),
                ('currency', models.CharField(default='CZK', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.customer')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('comment', 'Comment'), ('email_out', 'Email (Outbound)'), ('email_in', 'Email (Inbound)'), ('call', 'Call'), ('meeting', 'Meeting'), ('status_change', 'Status Change'), ('file_upload', 'File Upload'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed')], db_index=True, max_length=30)),
                ('content_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Type-specific structured data (see model docstring).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed / logged this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['due_date', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['firm', 'email'], name='crm_custome_firm_id_0e308d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['firm', 'status'], name='crm_lead_firm_id_15036e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['firm', 'assigned_to'], name='crm_lead_firm_id_35097c_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['lead', '-created_at'], name='crm_activit_lead_id_2ef199_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['lead', 'type'], name='crm_activit_lead_id_3f8aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['firm', 'is_completed'], name='crm_task_firm_id_0717cb_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['lead', 'is_completed'], name='crm_task_lead_id_1226bd_idx'),
        ),
    ]
