# Generated by Django 6.0.4 on 2026-05-03 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('firms', '0011_add_exchange_rate_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(choices=[('value_currency', 'Value / Currency'), ('date_range', 'Date Range'), ('expires_at', 'Expiry Date'), ('notes', 'Notes'), ('source', 'Source'), ('origin_record', 'Origin Record')], max_length=50)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'category field',
                'verbose_name_plural': 'category fields',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('purge_after', models.DateTimeField(blank=True, help_text='Scheduled timestamp for hard-delete. Null means never purge automatically.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'checkpoint',
                'verbose_name_plural': 'checkpoints',
                'ordering': ['date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRecord',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('purge_after', models.DateTimeField(blank=True, help_text='Scheduled timestamp for hard-delete. Null means never purge automatically.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('canceled', 'Canceled')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('referral', 'Referral'), ('cold_call', 'Cold Call'), ('social', 'Social'), ('other', 'Other')], default='web', max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated deal value.', max_digits=14, null=True)),
                ('currency', models.CharField(default='CZK', max_length=3)),
                ('canonical_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Value converted to firm.default_currency at time of last save.', max_digits=20, null=True)),
                ('canonical_currency', models.CharField(blank=True, help_text='Currency code of canonical_amount (= firm.default_currency at save time).', max_length=3)),
                ('canonical_rate_used', models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for canonical_amount calculation.', max_digits=20, null=True)),
                ('canonical_updated_at', models.DateTimeField(blank=True, help_text='When was canonical_amount last recalculated.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'pipeline record',
                'verbose_name_plural': 'pipeline records',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'stage',
                'verbose_name_plural': 'stages',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_firm_id_15036e_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_firm_id_35097c_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='lead',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='crm_activit_lead_id_2ef199_idx',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='crm_activit_lead_id_3f8aa7_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='crm_documen_firm_id_eb69e9_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='categoryfield',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='crm.category'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.category'),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company (from the address book) this lead belongs to.', limit_choices_to={'type': 'company'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_records', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='contact_person',
            field=models.ForeignKey(blank=True, help_text='The specific contact person at the company for this lead.', limit_choices_to={'type': 'person'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_person_records', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='activity',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='document',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='task',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.pipelinerecord'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to='crm.pipelinerecord'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.pipelinerecord'),
        ),
        migrations.AlterField(
            model_name='revenueitem',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_items', to='crm.pipelinerecord'),
        ),
        migrations.AlterField(
            model_name='sequenceenrollment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_enrollments', to='crm.pipelinerecord'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='crm.pipelinerecord'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['record', '-created_at'], name='crm_activit_record__5735d6_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['record', 'type'], name='crm_activit_record__d941ea_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['firm', 'record'], name='crm_documen_firm_id_4c1b79_idx'),
        ),
        migrations.AddField(
            model_name='stage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.category'),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.stage'),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='company',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='firm',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='document',
            name='lead',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('firm', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryfield',
            unique_together={('category', 'field_key')},
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('category', 'order')},
        ),
        migrations.AddIndex(
            model_name='pipelinerecord',
            index=models.Index(fields=['firm', 'status'], name='crm_pipelin_firm_id_b9dea7_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerecord',
            index=models.Index(fields=['firm', 'assigned_to'], name='crm_pipelin_firm_id_252ebd_idx'),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
