# Generated by Django 6.0.4 on 2026-05-04 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('crm', '0002_category_categoryfield_checkpoint_pipelinerecord_and_more'),
        ('crm', '0003_backfill_meeting_scheduled_tasks'),
        ('crm', '0004_rename_lead_created_trigger'),
    ]

    dependencies = [
        ('crm', '0001_initial'),
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who performed / logged this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityreaction',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='crm.activity'),
        ),
        migrations.AddField(
            model_name='activityreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='crm.automationrule'),
        ),
        migrations.AddField(
            model_name='category',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='categoryfield',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='crm.category'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, help_text='For person contacts: the company they work at.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='activity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='dashboardlayout',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layouts', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='dashboardlayout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailsequence',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='emailsequencestep',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crm.emailsequence'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firmproposalitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firmproposalitem',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadscoringrule',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='notification',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.category'),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company (from the address book) this lead belongs to.', limit_choices_to={'type': 'company'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_records', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='contact_person',
            field=models.ForeignKey(blank=True, help_text='The specific contact person at the company for this lead.', limit_choices_to={'type': 'person'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_person_records', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='document',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='activity',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='project',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='document',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.proposal'),
        ),
        migrations.AddField(
            model_name='activity',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.proposal'),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.proposal'),
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='proposaltemplateitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.proposaltemplate'),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_items', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_items', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedview',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='savedview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sequenceenrollment',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='sequenceenrollment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_enrollments', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='sequenceenrollment',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='crm.emailsequence'),
        ),
        migrations.AddField(
            model_name='stage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.category'),
        ),
        migrations.AddField(
            model_name='pipelinerecord',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.stage'),
        ),
        migrations.AddField(
            model_name='streamlineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_streamline_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streamlineitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streamlineitem',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='The user who last toggled this item to resolved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_streamline_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='approval_requested_from',
            field=models.ForeignKey(blank=True, help_text='The user who is asked to approve this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this task as done.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who originally created this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='task',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projects this task belongs to (multi-project support).', related_name='tasks', to='crm.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.proposal'),
        ),
        migrations.AddField(
            model_name='task',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, help_text='Points to the original (root) recurring task this instance was spawned from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_instances', to='crm.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users who receive notifications about changes to this task.', related_name='watched_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streamlineitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamline_items', to='crm.task'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to='crm.task'),
        ),
        migrations.AddField(
            model_name='document',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.task'),
        ),
        migrations.AddField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.task'),
        ),
        migrations.AddField(
            model_name='taskcustomfield',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcustomfield',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='taskcustomfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='crm.taskcustomfield'),
        ),
        migrations.AddField(
            model_name='taskcustomfieldvalue',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='crm.task'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_dependencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='from_task',
            field=models.ForeignKey(help_text='The task that is the source of the dependency.', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='crm.task'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='to_task',
            field=models.ForeignKey(help_text='The task that is the target of the dependency.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='crm.task'),
        ),
        migrations.AddField(
            model_name='taskfavourite',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='crm.task'),
        ),
        migrations.AddField(
            model_name='taskfavourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskpublicshare',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskpublicshare',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_share', to='crm.task'),
        ),
        migrations.AddField(
            model_name='taskreminder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crm.task'),
        ),
        migrations.AddField(
            model_name='taskreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='tasktimelog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='crm.task'),
        ),
        migrations.AddField(
            model_name='tasktimelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_time_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktimer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='crm.task'),
        ),
        migrations.AddField(
            model_name='tasktimer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_timers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='crm.pipelinerecord'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='crm.task'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activityreaction',
            index=models.Index(fields=['activity', 'created_at'], name='crm_activit_activit_f96409_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activityreaction',
            unique_together={('activity', 'user', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['firm', 'trigger', 'is_active'], name='crm_automat_firm_id_b9f616_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['rule', '-triggered_at'], name='crm_automat_rule_id_918e34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('firm', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryfield',
            unique_together={('category', 'field_key')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['firm', 'email'], name='crm_custome_firm_id_0e308d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardlayout',
            unique_together={('user', 'firm')},
        ),
        migrations.AddIndex(
            model_name='emailsequence',
            index=models.Index(fields=['firm', 'trigger_status', 'is_active'], name='crm_emailse_firm_id_e2507d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailsequencestep',
            unique_together={('sequence', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['firm', 'user', 'is_read'], name='crm_notific_firm_id_e9480d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='crm_notific_user_id_016eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['firm', 'lead', '-created_at'], name='crm_proposa_firm_id_47809e_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['firm', 'customer'], name='crm_proposa_firm_id_77c014_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['firm', 'status'], name='crm_proposa_firm_id_adb0a6_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user', 'push_enabled'], name='crm_pushsub_user_id_ff069e_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueitem',
            index=models.Index(fields=['firm', '-date'], name='crm_revenue_firm_id_58d66d_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueitem',
            index=models.Index(fields=['firm', 'lead'], name='crm_revenue_firm_id_ceb375_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueitem',
            index=models.Index(fields=['firm', 'customer'], name='crm_revenue_firm_id_9e1eb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedview',
            unique_together={('user', 'firm', 'entity', 'name')},
        ),
        migrations.AddIndex(
            model_name='sequenceenrollment',
            index=models.Index(fields=['status', 'next_send_at'], name='crm_sequenc_status_64c87f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('category', 'order')},
        ),
        migrations.AddIndex(
            model_name='pipelinerecord',
            index=models.Index(fields=['firm', 'status'], name='crm_pipelin_firm_id_b9dea7_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerecord',
            index=models.Index(fields=['firm', 'assigned_to'], name='crm_pipelin_firm_id_252ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['firm', 'is_completed'], name='crm_task_firm_id_0717cb_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['firm', 'status'], name='crm_task_firm_id_d41617_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['firm', 'priority'], name='crm_task_firm_id_313657_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['firm', 'is_archived'], name='crm_task_firm_id_b98aec_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['firm', 'approval_status'], name='crm_task_firm_id_0f41aa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['firm', 'kind'], name='crm_task_firm_id_f67c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['firm', 'auto_close_on_expiry', 'due_date'], name='crm_task_firm_id_88dcac_idx'),
        ),
        migrations.AddIndex(
            model_name='streamlineitem',
            index=models.Index(fields=['task', 'kind', 'order'], name='crm_streaml_task_id_28de4b_idx'),
        ),
        migrations.AddIndex(
            model_name='streamlineitem',
            index=models.Index(fields=['task', 'kind', 'is_resolved'], name='crm_streaml_task_id_3bbf37_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['firm', '-date'], name='crm_expense_firm_id_f1ccc1_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['firm', 'lead'], name='crm_expense_firm_id_36e872_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['firm', 'customer'], name='crm_expense_firm_id_634f16_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['firm', '-created_at'], name='crm_documen_firm_id_8b2579_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['firm', 'record'], name='crm_documen_firm_id_4c1b79_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['firm', 'customer'], name='crm_documen_firm_id_ded421_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['firm', 'task'], name='crm_documen_firm_id_a28252_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['record', '-created_at'], name='crm_activit_record__5735d6_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['record', 'type'], name='crm_activit_record__d941ea_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['customer', '-created_at'], name='crm_activit_cust_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['proposal', '-created_at'], name='crm_activit_prop_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['task', '-created_at'], name='crm_activit_task_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['task', 'type'], name='crm_activit_task_type_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcustomfield',
            index=models.Index(fields=['firm', 'position'], name='crm_taskcf_firm_pos_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskcustomfieldvalue',
            unique_together={('task', 'field')},
        ),
        migrations.AddIndex(
            model_name='taskdependency',
            index=models.Index(fields=['from_task', 'type'], name='crm_taskdep_from_ta_374e58_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdependency',
            index=models.Index(fields=['to_task', 'type'], name='crm_taskdep_to_task_136b77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('from_task', 'to_task', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='taskfavourite',
            unique_together={('task', 'user')},
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['firm', 'name'], name='crm_tasktem_firm_id_d97726_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktimelog',
            index=models.Index(fields=['task', '-logged_at'], name='crm_tasktim_task_id_115031_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktimelog',
            index=models.Index(fields=['user', '-logged_at'], name='crm_tasktim_user_id_6c65e8_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktimer',
            index=models.Index(fields=['user', 'stopped_at'], name='crm_tasktim_user_id_c4f3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktimer',
            index=models.Index(fields=['task', 'user', 'stopped_at'], name='crm_tasktim_task_id_ea442f_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['firm', 'user', '-created_at'], name='crm_timeent_firm_id_4e94cc_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['firm', 'lead'], name='crm_timeent_firm_id_473226_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['firm', 'customer'], name='crm_timeent_firm_id_2037a0_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['firm', 'task'], name='crm_timeent_firm_id_e76f5c_idx'),
        ),
    ]
