# Generated by Django 6.0.4 on 2026-04-25 22:29

import crm.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_notification'),
        ('firms', '0003_apitoken_webhook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('leads', 'Leads'), ('customers', 'Customers')], default='leads', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('file', models.FileField(upload_to=crm.models._import_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('total', models.PositiveIntegerField(default=0, help_text='Total rows in CSV (excluding header).')),
                ('processed', models.PositiveIntegerField(default=0, help_text='Rows successfully imported so far.')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='Rows that could not be imported.')),
                ('errors_json', models.JSONField(blank=True, default=list, help_text='List of {row, error} dicts for rows that failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'import job',
                'verbose_name_plural': 'import jobs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='crm_notific_firm_id_e9480d_idx',
            old_name='crm_notif_firm_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='crm_notific_user_id_016eb8_idx',
            old_name='crm_notif_user_created_idx',
        ),
        migrations.AddField(
            model_name='importjob',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
