# Generated by Django 6.0.4 on 2026-04-25 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_importjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('canceled', 'Canceled')], help_text='Empty string on the very first entry (initial status at creation).', max_length=20)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('canceled', 'Canceled')], max_length=20)),
                ('changed_at', models.DateTimeField(db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_status_changes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='crm.lead')),
            ],
            options={
                'verbose_name': 'lead status history',
                'verbose_name_plural': 'lead status histories',
                'ordering': ['lead', 'changed_at'],
                'indexes': [models.Index(fields=['lead', 'changed_at'], name='crm_leadsta_lead_id_3173b0_idx'), models.Index(fields=['lead', 'to_status'], name='crm_leadsta_lead_id_e30db9_idx')],
            },
        ),
    ]
