# Generated by Django 6.0.4 on 2026-05-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_categoryfield_extended'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expenseitem',
            new_name='crm_expense_firm_id_b9a20d_idx',
            old_name='crm_expense_firm_id_36e872_idx',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='crm_proposa_firm_id_a098c9_idx',
            old_name='crm_proposa_firm_id_47809e_idx',
        ),
        migrations.RenameIndex(
            model_name='revenueitem',
            new_name='crm_revenue_firm_id_50bd3f_idx',
            old_name='crm_revenue_firm_id_ceb375_idx',
        ),
        migrations.RenameIndex(
            model_name='timeentry',
            new_name='crm_timeent_firm_id_6e4509_idx',
            old_name='crm_timeent_firm_id_473226_idx',
        ),
    ]
