# Generated by Django 6.0.4 on 2026-04-26 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_add_lead_status_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField(help_text='Browser public key (base64url).')),
                ('auth', models.TextField(help_text='Authentication secret (base64url).')),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('push_enabled', models.BooleanField(db_index=True, default=True, help_text='Set to False to soft-disable without removing the subscription.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'push subscription',
                'verbose_name_plural': 'push subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'push_enabled'], name='crm_pushsub_user_id_ff069e_idx')],
            },
        ),
    ]
