# Generated by Django 6.0.5 on 2026-05-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_category_record_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted')], db_index=True, default='public', help_text="Controls who can see this activity. 'public' (default) = visible to all members who can see the parent record. 'restricted' = visible only to users with scope=team or scope=all, or the activity author.", max_length=10),
        ),
    ]
