# Generated by Django 6.0.4 on 2026-04-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_v2_4_plugins'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailsequence',
            new_name='crm_emailse_firm_id_e2507d_idx',
            old_name='crm_emailseq_firm_trigger_idx',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='crm_proposa_lead_id_3a1840_idx',
            old_name='crm_proposal_lead_created_idx',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='crm_proposa_firm_id_adb0a6_idx',
            old_name='crm_proposal_firm_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sequenceenrollment',
            new_name='crm_sequenc_status_64c87f_idx',
            old_name='crm_seqenroll_status_next_idx',
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('comment', 'Comment'), ('email_out', 'Email (Outbound)'), ('email_in', 'Email (Inbound)'), ('call', 'Call'), ('meeting', 'Meeting'), ('status_change', 'Status Change'), ('file_upload', 'File Upload'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='dashboardlayout',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailsequence',
            name='trigger_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('canceled', 'Canceled')], db_index=True, help_text='Lead status that triggers enrollment into this sequence.', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailsequencestep',
            name='body_template',
            field=models.TextField(help_text='Plain-text email body. Supports {{lead_title}}, {{customer_name}} placeholders.'),
        ),
        migrations.AlterField(
            model_name='emailsequencestep',
            name='delay_days',
            field=models.PositiveIntegerField(default=0, help_text='Days after the previous step (or after enrollment for step 1) before this email is sent.'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the public link expires.  Null = link never auto-expires.', null=True),
        ),
        migrations.AlterField(
            model_name='savedview',
            name='filters',
            field=models.JSONField(default=dict, help_text='Serialised filter state, e.g. {"status": "new", "source": "web"}.'),
        ),
        migrations.AlterField(
            model_name='sequenceenrollment',
            name='next_send_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the next sequence email should be dispatched.', null=True),
        ),
    ]
