# Generated by Django 6.0.5 on 2026-05-10 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_activity_visibility'),
        ('firms', '0014_invitation_category_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('scope_type', models.CharField(choices=[('firm', 'Firm'), ('category', 'Category'), ('stage', 'Stage'), ('stage_transition', 'Stage transition')], default='firm', max_length=30)),
                ('trigger_type', models.CharField(choices=[('record.created', 'Record created'), ('record.updated', 'Record updated'), ('record.field_changed', 'Record field changed'), ('record.category_field_changed', 'Record category field changed'), ('record.stage_change_requested', 'Record stage change requested'), ('record.stage_changed', 'Record stage changed'), ('stage.entered', 'Stage entered'), ('stage.left', 'Stage left'), ('streamline.activity_created', 'Streamline activity created'), ('streamline.activity_updated', 'Streamline activity updated'), ('streamline.activity_deleted', 'Streamline activity deleted'), ('streamline.checklist_item_completed', 'Streamline checklist item completed'), ('streamline.checklist_item_reopened', 'Streamline checklist item reopened'), ('streamline.file_uploaded', 'Streamline file uploaded'), ('task.completed', 'Task completed'), ('task.reopened', 'Task reopened'), ('proposal.signed', 'Proposal signed'), ('proposal.rejected', 'Proposal rejected'), ('manual.evaluation_requested', 'Manual evaluation requested')], db_index=True, max_length=50)),
                ('condition_tree', models.JSONField(blank=True, default=dict)),
                ('effect', models.CharField(choices=[('block', 'Block'), ('warning', 'Warning'), ('recommendation', 'Recommendation'), ('activate_scenario', 'Activate scenario'), ('complete_requirement', 'Complete requirement')], default='block', max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='error', max_length=10)),
                ('effect_config', models.JSONField(blank=True, default=dict)),
                ('activity_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_rules', to='crm.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_condition_rules', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm')),
                ('source_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_rules_source', to='crm.stage')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_rules', to='crm.stage')),
                ('target_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_rules_target', to='crm.stage')),
            ],
            options={
                'verbose_name': 'condition rule',
                'verbose_name_plural': 'condition rules',
                'ordering': ['priority', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activation_condition', models.JSONField(blank=True, default=dict)),
                ('completion_condition', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_scenarios', to='crm.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stage_scenarios', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm')),
                ('recommended_next_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_by_stage_scenarios', to='crm.stage')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='crm.stage')),
            ],
            options={
                'verbose_name': 'stage scenario',
                'verbose_name_plural': 'stage scenarios',
                'ordering': ['priority', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('requirement_type', models.CharField(choices=[('field', 'Field'), ('category_field', 'Category field'), ('activity', 'Activity'), ('checklist', 'Checklist'), ('attachment', 'Attachment'), ('task', 'Task'), ('custom', 'Custom')], default='custom', max_length=40)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('blocking', models.BooleanField(default=True)),
                ('visible_to_user', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='crm.stagescenario')),
            ],
            options={
                'verbose_name': 'stage requirement',
                'verbose_name_plural': 'stage requirements',
                'ordering': ['sort_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleEvaluationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('record.created', 'Record created'), ('record.updated', 'Record updated'), ('record.field_changed', 'Record field changed'), ('record.category_field_changed', 'Record category field changed'), ('record.stage_change_requested', 'Record stage change requested'), ('record.stage_changed', 'Record stage changed'), ('stage.entered', 'Stage entered'), ('stage.left', 'Stage left'), ('streamline.activity_created', 'Streamline activity created'), ('streamline.activity_updated', 'Streamline activity updated'), ('streamline.activity_deleted', 'Streamline activity deleted'), ('streamline.checklist_item_completed', 'Streamline checklist item completed'), ('streamline.checklist_item_reopened', 'Streamline checklist item reopened'), ('streamline.file_uploaded', 'Streamline file uploaded'), ('task.completed', 'Task completed'), ('task.reopened', 'Task reopened'), ('proposal.signed', 'Proposal signed'), ('proposal.rejected', 'Proposal rejected'), ('manual.evaluation_requested', 'Manual evaluation requested')], db_index=True, max_length=50)),
                ('input_context', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('blocked', 'Blocked'), ('warning', 'Warning'), ('error', 'Error'), ('scenario_activated', 'Scenario activated'), ('requirement_completed', 'Requirement completed')], max_length=30)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_evaluations', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_evaluation_logs', to='firms.firm')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_evaluation_logs', to='crm.pipelinerecord')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_logs', to='crm.conditionrule')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_logs', to='crm.stagerequirement')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_logs', to='crm.stagescenario')),
            ],
            options={
                'verbose_name': 'rule evaluation log',
                'verbose_name_plural': 'rule evaluation logs',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conditionrule',
            index=models.Index(fields=['firm', 'is_active', 'trigger_type', 'priority'], name='crm_conditi_firm_id_210ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='conditionrule',
            index=models.Index(fields=['firm', 'category', 'is_active'], name='crm_conditi_firm_id_d190fa_idx'),
        ),
        migrations.AddIndex(
            model_name='conditionrule',
            index=models.Index(fields=['firm', 'stage', 'trigger_type'], name='crm_conditi_firm_id_f28fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='conditionrule',
            index=models.Index(fields=['firm', 'trigger_type', 'activity_type', 'is_active'], name='crm_conditi_firm_id_352849_idx'),
        ),
        migrations.AddIndex(
            model_name='stagescenario',
            index=models.Index(fields=['firm', 'category', 'stage', 'is_active', 'priority'], name='crm_stagesc_firm_id_550aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='stagerequirement',
            index=models.Index(fields=['scenario', 'blocking', 'sort_order'], name='crm_stagere_scenari_7eb749_idx'),
        ),
        migrations.AddIndex(
            model_name='stagerequirement',
            index=models.Index(fields=['firm', 'scenario'], name='crm_stagere_firm_id_c4c951_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleevaluationlog',
            index=models.Index(fields=['firm', 'trigger_type', '-evaluated_at'], name='crm_ruleeva_firm_id_f665ef_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleevaluationlog',
            index=models.Index(fields=['firm', 'record', '-evaluated_at'], name='crm_ruleeva_firm_id_df116d_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleevaluationlog',
            index=models.Index(fields=['rule', '-evaluated_at'], name='crm_ruleeva_rule_id_35b3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleevaluationlog',
            index=models.Index(fields=['scenario', '-evaluated_at'], name='crm_ruleeva_scenari_57ae29_idx'),
        ),
    ]
