# Generated by Django 6.0.5 on 2026-05-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_conditionrule_stagescenario_stagerequirement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagerequirement",
            name="next_step_on_met",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_by_met",
                to="crm.stagerequirement",
            ),
        ),
        migrations.AddField(
            model_name="stagerequirement",
            name="next_step_on_unmet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_by_unmet",
                to="crm.stagerequirement",
            ),
        ),
    ]
