# Generated by Django 6.0.4 on 2026-04-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_v2_5_automation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='automationrule',
            new_name='crm_automat_firm_id_b9f616_idx',
            old_name='crm_automat_firm_id_trigger_active_idx',
        ),
        migrations.RenameIndex(
            model_name='automationrun',
            new_name='crm_automat_rule_id_918e34_idx',
            old_name='crm_automat_rule_id_triggered_idx',
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='actions',
            field=models.JSONField(default=list, help_text="Ordered list of action objects. Each action has a 'type' key: send_email, create_task, update_field, call_webhook, run_plugin_action."),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='conditions',
            field=models.JSONField(blank=True, default=list, help_text='List of {field, operator, value} condition objects. Supported operators: eq, neq, gt, gte, lt, lte, contains. All conditions must match (AND).'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_config',
            field=models.JSONField(blank=True, default=dict, help_text='Trigger-specific configuration. LEAD_INACTIVE: {inactive_days: 30}. TASK_OVERDUE: {warning_days: 1}.'),
        ),
    ]
