# Generated by Django 6.0.4 on 2026-04-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_task_created_by_taskcomment_taskattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskattachment',
            new_name='crm_taskatt_task_id_daa14b_idx',
            old_name='crm_taskatt_task_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='taskcomment',
            new_name='crm_taskcom_task_id_0fd96b_idx',
            old_name='crm_taskcom_task_id_created_idx',
        ),
    ]
