# Generated by Django 6.0.4 on 2026-04-27 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_rename_crm_taskatt_task_id_created_idx_crm_taskatt_task_id_daa14b_idx_and_more'),
        ('firms', '0007_alter_pluginconfig_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskFavourite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'task favourite',
                'verbose_name_plural': 'task favourites',
            },
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remind_at', models.DateTimeField(db_index=True)),
                ('is_sent', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'task reminder',
                'verbose_name_plural': 'task reminders',
                'ordering': ['remind_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='crm_task_lead_id_1226bd_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this task as done.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='task',
            name='description_added_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the rich-text description was last set.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description_html',
            field=models.TextField(blank=True, help_text='Rich-text HTML description from TipTap editor.'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date_end',
            field=models.DateTimeField(blank=True, help_text="End of date range when 'Rozsah termínů' toggle is on.", null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Parent task for subtask hierarchy (prepared for Phase 3).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='crm.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.proposal'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='todo', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tag strings.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Plain-text description (legacy).'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='project',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='task',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projects this task belongs to (multi-project support).', related_name='tasks', to='crm.project'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['firm', 'status'], name='crm_task_firm_id_d41617_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['firm', 'priority'], name='crm_task_firm_id_313657_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['firm', 'is_archived'], name='crm_task_firm_id_b98aec_idx'),
        ),
        migrations.AddField(
            model_name='taskfavourite',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='crm.task'),
        ),
        migrations.AddField(
            model_name='taskfavourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskreminder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crm.task'),
        ),
        migrations.AddField(
            model_name='taskreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='taskfavourite',
            unique_together={('task', 'user')},
        ),
    ]
