# Generated by Django 6.0.4 on 2026-04-27 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_phase1_flexible_task_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('is_checked', models.BooleanField(db_index=True, default=False)),
                ('position', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='crm.task')),
            ],
            options={
                'verbose_name': 'task checklist item',
                'verbose_name_plural': 'task checklist items',
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['task', 'position'], name='crm_taskche_task_id_02650f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('blocks', 'Blocks'), ('related_to', 'Related To')], default='blocks', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_dependencies', to=settings.AUTH_USER_MODEL)),
                ('from_task', models.ForeignKey(help_text='The task that is the source of the dependency.', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='crm.task')),
                ('to_task', models.ForeignKey(help_text='The task that is the target of the dependency.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='crm.task')),
            ],
            options={
                'verbose_name': 'task dependency',
                'verbose_name_plural': 'task dependencies',
                'indexes': [models.Index(fields=['from_task', 'type'], name='crm_taskdep_from_ta_374e58_idx'), models.Index(fields=['to_task', 'type'], name='crm_taskdep_to_task_136b77_idx')],
                'unique_together': {('from_task', 'to_task', 'type')},
            },
        ),
    ]
