# Generated by Django 6.0.4 on 2026-04-27 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_phase2_timeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPublicShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'task public share',
                'verbose_name_plural': 'task public shares',
            },
        ),
        migrations.RemoveConstraint(
            model_name='taskcommentreaction',
            name='unique_task_comment_reaction',
        ),
        migrations.RenameIndex(
            model_name='tasktimelineentry',
            new_name='crm_tasktim_task_id_39fdc0_idx',
            old_name='crm_taskti_task_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='tasktimelineentry',
            new_name='crm_tasktim_task_id_bea670_idx',
            old_name='crm_taskti_task_id_evtype_idx',
        ),
        migrations.AlterField(
            model_name='tasktimelineentry',
            name='author',
            field=models.ForeignKey(blank=True, help_text='User who created this entry (null for automated system events).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_timeline_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasktimelineentry',
            name='content_html',
            field=models.TextField(blank=True, help_text='Sanitised HTML from TipTap; only populated for comment entries.'),
        ),
        migrations.AlterField(
            model_name='tasktimelineentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Structured event data (varies by event_type).'),
        ),
        migrations.AlterField(
            model_name='tasktimelineentry',
            name='parent_entry',
            field=models.ForeignKey(blank=True, help_text='Parent comment entry for reply threading.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='crm.tasktimelineentry'),
        ),
        migrations.AlterField(
            model_name='taskvoiceattachment',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the recording in seconds (provided by the client).', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='taskcommentreaction',
            unique_together={('entry', 'user', 'emoji')},
        ),
        migrations.AddField(
            model_name='taskpublicshare',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskpublicshare',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_share', to='crm.task'),
        ),
    ]
