# Generated by Django 6.0.4 on 2026-04-27 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_phase5_task_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated time budget in minutes (Phase 6).', null=True),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger',
            field=models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_status_change', 'Lead Status Changed'), ('task_overdue', 'Task Overdue'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('proposal_sent', 'Proposal Sent'), ('proposal_accepted', 'Proposal Accepted'), ('lead_inactive', 'Lead Inactive (N days)'), ('webhook_received', 'Custom Webhook Received')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='TaskTimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logged_at', models.DateTimeField(db_index=True, help_text='When the work was performed (may be back-dated by the user).')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Worked time in minutes.')),
                ('description', models.TextField(blank=True, help_text='Optional note about what was worked on.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='crm.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task time log',
                'verbose_name_plural': 'task time logs',
                'ordering': ['-logged_at', '-created_at'],
                'indexes': [models.Index(fields=['task', '-logged_at'], name='crm_tasktim_task_id_115031_idx'), models.Index(fields=['user', '-logged_at'], name='crm_tasktim_user_id_6c65e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskTimer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('stopped_at', models.DateTimeField(blank=True, db_index=True, help_text='Null while the timer is still running.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='crm.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_timers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task timer',
                'verbose_name_plural': 'task timers',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'stopped_at'], name='crm_tasktim_user_id_c4f3a4_idx'), models.Index(fields=['task', 'user', 'stopped_at'], name='crm_tasktim_task_id_ea442f_idx')],
            },
        ),
    ]
