# Generated by Django 6.0.4 on 2026-04-27 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_rename_saved_view_entities'),
        ('firms', '0007_alter_pluginconfig_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text="Amount in the firm's default currency.", max_digits=14)),
                ('currency', models.CharField(default='CZK', max_length=3)),
                ('date', models.DateField(db_index=True, help_text='Date the expense was incurred.')),
                ('recurrence', models.CharField(choices=[('once', 'Once'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], db_index=True, default='once', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'expense item',
                'verbose_name_plural': 'expense items',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text="Amount in the firm's default currency.", max_digits=14)),
                ('currency', models.CharField(default='CZK', max_length=3)),
                ('date', models.DateField(db_index=True, help_text='Date the revenue was recognised.')),
                ('recurrence', models.CharField(choices=[('once', 'Once'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], db_index=True, default='once', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'revenue item',
                'verbose_name_plural': 'revenue items',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, help_text='Start of the work session (from timer); null for manual entries.', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='End of the work session (from timer); null while timer is running or for manual entries.', null=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Total worked time in minutes.')),
                ('description', models.TextField(blank=True, help_text='Optional note about the work performed.')),
                ('is_billable', models.BooleanField(db_index=True, default=True, help_text='Whether this time should be included in billing/invoicing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'time entry',
                'verbose_name_plural': 'time entries',
                'ordering': ['-started_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'contact', 'verbose_name_plural': 'directory'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'opportunity', 'verbose_name_plural': 'opportunities'},
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='crm_task_firm_id_0f41aa_idx',
            old_name='crm_task_firm_approval_idx',
        ),
        migrations.RenameIndex(
            model_name='tasktemplate',
            new_name='crm_tasktem_firm_id_d97726_idx',
            old_name='crm_tasktemplate_firm_name_idx',
        ),
        migrations.AlterField(
            model_name='taskcustomfield',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of option strings for dropdown type.'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to='crm.task'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_items', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_items', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='crm.task'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['firm', '-date'], name='crm_expense_firm_id_f1ccc1_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['firm', 'lead'], name='crm_expense_firm_id_36e872_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['firm', 'customer'], name='crm_expense_firm_id_634f16_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueitem',
            index=models.Index(fields=['firm', '-date'], name='crm_revenue_firm_id_58d66d_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueitem',
            index=models.Index(fields=['firm', 'lead'], name='crm_revenue_firm_id_ceb375_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueitem',
            index=models.Index(fields=['firm', 'customer'], name='crm_revenue_firm_id_9e1eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['firm', 'user', '-created_at'], name='crm_timeent_firm_id_4e94cc_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['firm', 'lead'], name='crm_timeent_firm_id_473226_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['firm', 'customer'], name='crm_timeent_firm_id_2037a0_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['firm', 'task'], name='crm_timeent_firm_id_e76f5c_idx'),
        ),
    ]
