# Generated by Django 6.0.4 on 2026-04-28 00:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_phase4_0_erp_models'),
        ('firms', '0007_alter_pluginconfig_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Naplánováno'), ('in_progress', 'Probíhá'), ('on_hold', 'Pozastaveno'), ('done', 'Dokončeno'), ('cancelled', 'Zrušeno')], db_index=True, default='planned', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Planned or actual start date.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Planned or actual end date.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_realizations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realizations', to='crm.customer')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm')),
                ('lead', models.ForeignKey(blank=True, help_text='The winning opportunity that spawned this realization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realizations', to='crm.lead')),
            ],
            options={
                'verbose_name': 'realization',
                'verbose_name_plural': 'realizations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('realization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='crm.realization')),
            ],
            options={
                'verbose_name': 'milestone',
                'verbose_name_plural': 'milestones',
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='realization',
            index=models.Index(fields=['firm', 'status'], name='crm_realiza_firm_id_2925bf_idx'),
        ),
        migrations.AddIndex(
            model_name='realization',
            index=models.Index(fields=['firm', 'assigned_to'], name='crm_realiza_firm_id_1f5162_idx'),
        ),
        migrations.AddIndex(
            model_name='realization',
            index=models.Index(fields=['firm', 'lead'], name='crm_realiza_firm_id_b9e3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['realization', 'date'], name='crm_milesto_realiza_9c369b_idx'),
        ),
    ]
