# Generated by Django 6.0.4 on 2026-04-28 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_phase4_1_realization'),
        ('firms', '0007_alter_pluginconfig_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='realization',
            field=models.ForeignKey(blank=True, help_text='Optional Realization this entry is linked to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='crm.realization'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['firm', 'realization'], name='crm_timeent_firm_id_b1ef53_idx'),
        ),
    ]
