# Generated by Django 6.0.4 on 2026-04-28 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_phase4_1_timeentry_realization'),
        ('firms', '0007_alter_pluginconfig_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('sla', 'SLA'), ('warranty', 'Záruka'), ('retention', 'Retence'), ('care', 'Péče')], db_index=True, default='care', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Otevřeno'), ('in_progress', 'Řeší se'), ('waiting', 'Čeká na zákazníka'), ('closed', 'Uzavřeno')], db_index=True, default='open', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='SLA or warranty expiry date/time.  Used for colour indicators and escalation triggers.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_management', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_records', to='crm.customer')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm')),
                ('realization', models.ForeignKey(blank=True, help_text='The realization that spawned this management record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_records', to='crm.realization')),
            ],
            options={
                'verbose_name': 'management',
                'verbose_name_plural': 'management records',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['firm', 'status'], name='crm_managem_firm_id_e796ed_idx'), models.Index(fields=['firm', 'type'], name='crm_managem_firm_id_f7193f_idx'), models.Index(fields=['firm', 'assigned_to'], name='crm_managem_firm_id_fcf999_idx'), models.Index(fields=['firm', 'realization'], name='crm_managem_firm_id_c6c933_idx')],
            },
        ),
    ]
