# Generated by Django 6.0.4 on 2026-04-28 08:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_phase4_2_management'),
        ('firms', '0007_alter_pluginconfig_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmProposalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Discount percentage (0–100).', max_digits=5)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='VAT rate percentage (e.g. 21 for 21%).', max_digits=5)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'firm proposal item',
                'verbose_name_plural': 'firm proposal items',
                'ordering': ['position', 'description'],
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='proposal',
            name='crm_proposa_lead_id_3a1840_idx',
        ),
        migrations.AddField(
            model_name='proposal',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.management'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='realization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.realization'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('comment', 'Comment'), ('email_out', 'Email (Outbound)'), ('email_in', 'Email (Inbound)'), ('call', 'Call'), ('meeting', 'Meeting'), ('status_change', 'Status Change'), ('file_upload', 'File Upload'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('proposal_created', 'Proposal Created'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.lead'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['firm', 'lead', '-created_at'], name='crm_proposa_firm_id_47809e_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['firm', 'customer'], name='crm_proposa_firm_id_77c014_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['firm', 'realization'], name='crm_proposa_firm_id_7eae5a_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['firm', 'management'], name='crm_proposa_firm_id_578639_idx'),
        ),
        migrations.AddField(
            model_name='firmproposalitem',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm'),
        ),
    ]
