# Generated by Django 6.0.4 on 2026-04-28 09:04

import crm.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_phase4_3_proposal_standalone_firmproposalitem'),
        ('firms', '0007_alter_pluginconfig_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the document (defaults to original filename).', max_length=255)),
                ('file', models.FileField(upload_to=crm.models._document_upload_to)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.customer')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='firms.firm')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.lead')),
                ('management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.management')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.proposal')),
                ('realization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.realization')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.task')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['firm', '-created_at'], name='crm_documen_firm_id_8b2579_idx'), models.Index(fields=['firm', 'lead'], name='crm_documen_firm_id_eb69e9_idx'), models.Index(fields=['firm', 'customer'], name='crm_documen_firm_id_ded421_idx'), models.Index(fields=['firm', 'realization'], name='crm_documen_firm_id_14314c_idx'), models.Index(fields=['firm', 'management'], name='crm_documen_firm_id_24bdae_idx'), models.Index(fields=['firm', 'task'], name='crm_documen_firm_id_a28252_idx')],
            },
        ),
    ]
