# Generated by Django 6.0.4 on 2026-04-28 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_phase4_3_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, help_text='For person contacts: the company they work at.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='dic',
            field=models.CharField(blank=True, help_text='DIČ — tax identification number', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='ico',
            field=models.CharField(blank=True, help_text='IČO — company registration number', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('person', 'Person'), ('company', 'Company')], db_index=True, default='person', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
