# Generated by Django 6.0.4 on 2026-04-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_phase4_4_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='condition_logic',
            field=models.CharField(default='and', help_text="'and' — all conditions must match; 'or' — any condition must match.", max_length=3),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='conditions',
            field=models.JSONField(blank=True, default=list, help_text="List of {field, operator, value} condition objects. Supported operators: eq, neq, gt, gte, lt, lte, contains. All conditions must match (AND) unless condition_logic is 'or'."),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger',
            field=models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_status_change', 'Lead Status Changed'), ('task_overdue', 'Task Overdue'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('proposal_sent', 'Proposal Sent'), ('proposal_accepted', 'Proposal Accepted'), ('lead_inactive', 'Lead Inactive (N days)'), ('webhook_received', 'Custom Webhook Received'), ('realization_status_change', 'Realization Status Changed'), ('sla_expiring', 'SLA / Warranty Expiring (N days)'), ('contact_created', 'Contact Created'), ('milestone_completed', 'Milestone Completed')], db_index=True, max_length=50),
        ),
    ]
