# Generated by Django 6.0.4 on 2026-04-29 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_alter_activity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'activity reaction',
                'verbose_name_plural': 'activity reactions',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.task'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('comment', 'Comment'), ('email_out', 'Email (Outbound)'), ('email_in', 'Email (Inbound)'), ('call', 'Call'), ('meeting', 'Meeting'), ('status_change', 'Status Change'), ('file_upload', 'File Upload'), ('task_created', 'Task Created'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_archived', 'Task Archived'), ('sub_task_added', 'Sub-task Added'), ('priority_change', 'Priority Change'), ('assignee_change', 'Assignee Change'), ('due_date_change', 'Due Date Change'), ('approval_requested', 'Approval Requested'), ('approval_resolved', 'Approval Resolved'), ('time_logged', 'Time Logged'), ('checklist_item_checked', 'Checklist Item Checked'), ('voice_memo', 'Voice Memo'), ('proposal_created', 'Proposal Created'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('entity_change', 'Field Changed')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['task', '-created_at'], name='crm_activit_task_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['task', 'type'], name='crm_activit_task_type_idx'),
        ),
        migrations.AddField(
            model_name='activityreaction',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='crm.activity'),
        ),
        migrations.AddField(
            model_name='activityreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activityreaction',
            index=models.Index(fields=['activity', 'created_at'], name='crm_activit_activit_f96409_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activityreaction',
            unique_together={('activity', 'user', 'emoji')},
        ),
    ]
