# Generated by Django 6.0.4 on 2026-04-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_phase6_streamline_bonus_activity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False, help_text='If true, this activity is internal-only and may be hidden from external-facing views (customer portal, share-out feeds). Permission gating itself is handled at the serializer / view level — this field is purely a flag.'),
        ),
    ]
