# Generated by Django 6.0.4 on 2026-04-30 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_activity_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='management',
            field=models.ForeignKey(blank=True, help_text='Optional link to a Management record. SET_NULL on delete so task survives.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.management'),
        ),
        migrations.AddField(
            model_name='task',
            name='realization',
            field=models.ForeignKey(blank=True, help_text='Optional link to a Realization. SET_NULL on delete so task survives.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.realization'),
        ),
    ]
