# Generated by Django 6.0.4 on 2026-04-30 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_task_management_task_realization'),
        ('firms', '0009_remove_firm_fakturoid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attendees',
            field=models.JSONField(blank=True, default=list, help_text='List of attendees for calendar-bound tasks.  Items may be either internal user IDs or external e-mail addresses / handles.'),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_close_on_expiry',
            field=models.BooleanField(db_index=True, default=False, help_text='When True, the task is automatically transitioned to status ``EXPIRED`` by the background job once its ``due_date`` has elapsed past the configured grace period and no manual outcome has been logged.'),
        ),
        migrations.AddField(
            model_name='task',
            name='kind',
            field=models.CharField(choices=[('generic', 'Generic'), ('call', 'Call'), ('meeting', 'Meeting'), ('email_followup', 'Email follow-up')], db_index=True, default='generic', help_text='What kind of task this is.  Calendar-bound kinds (call, meeting) act as parent objects for scheduled activities and may auto-close on expiry.', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Physical address or virtual meeting URL for calendar-bound tasks.', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('comment', 'Comment'), ('email_out', 'Email (Outbound)'), ('email_in', 'Email (Inbound)'), ('call', 'Call'), ('meeting', 'Meeting'), ('status_change', 'Status Change'), ('file_upload', 'File Upload'), ('task_created', 'Task Created'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_archived', 'Task Archived'), ('sub_task_added', 'Sub-task Added'), ('priority_change', 'Priority Change'), ('assignee_change', 'Assignee Change'), ('due_date_change', 'Due Date Change'), ('approval_requested', 'Approval Requested'), ('approval_resolved', 'Approval Resolved'), ('time_logged', 'Time Logged'), ('checklist_item_checked', 'Checklist Item Checked'), ('voice_memo', 'Voice Memo'), ('proposal_created', 'Proposal Created'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('proposal_viewed', 'Proposal Viewed'), ('entity_change', 'Field Changed'), ('sms_out', 'SMS (Outbound)'), ('sms_in', 'SMS (Inbound)'), ('whatsapp_out', 'WhatsApp (Outbound)'), ('whatsapp_in', 'WhatsApp (Inbound)'), ('chat', 'Chat Message'), ('meeting_scheduled', 'Meeting Scheduled'), ('call_scheduled', 'Call Scheduled'), ('task_expired', 'Task Expired'), ('link', 'Link'), ('payment_received', 'Payment Received'), ('invoice_sent', 'Invoice Sent'), ('signature_requested', 'Signature Requested'), ('signature_completed', 'Signature Completed'), ('ai_summary', 'AI Summary'), ('ai_suggested_action', 'AI Suggested Action'), ('system_note', 'System Note'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('mention', 'Mention'), ('pinned', 'Pinned'), ('unpinned', 'Unpinned')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='todo', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['firm', 'kind'], name='crm_task_firm_id_f67c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['firm', 'auto_close_on_expiry', 'due_date'], name='crm_task_firm_id_88dcac_idx'),
        ),
    ]
