# Generated by Django 6.0.4 on 2026-04-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_backfill_meeting_scheduled_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='outcome_prompted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the assignee/watchers were prompted to log the outcome of this calendar task (held / rescheduled / no_show). Set by the auto-expire job after ``due_date_end`` and cleared when the task is rescheduled. Null means we have not asked yet.', null=True),
        ),
    ]
