# Generated by Django 6.0.4 on 2026-05-01 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_streamline_item_unification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='streamlineitem',
            new_name='crm_streaml_task_id_28de4b_idx',
            old_name='crm_streaml_task_id_kind_order_idx',
        ),
        migrations.RenameIndex(
            model_name='streamlineitem',
            new_name='crm_streaml_task_id_3bbf37_idx',
            old_name='crm_streaml_task_id_kind_resolved_idx',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='checklist_items',
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='default_items',
            field=models.JSONField(blank=True, default=list, help_text='List of default streamline items: [{"kind": "todo|subtask", "text": "...", "position": 0}].'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('comment', 'Comment'), ('email_out', 'Email (Outbound)'), ('email_in', 'Email (Inbound)'), ('call', 'Call'), ('meeting', 'Meeting'), ('status_change', 'Status Change'), ('file_upload', 'File Upload'), ('task_created', 'Task Created'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_archived', 'Task Archived'), ('streamline_items_added', 'Streamline Items Added'), ('streamline_item_resolved', 'Streamline Item Resolved'), ('streamline_item_reopened', 'Streamline Item Reopened'), ('todo_items_added', 'Todo Items Added'), ('priority_change', 'Priority Change'), ('assignee_change', 'Assignee Change'), ('due_date_change', 'Due Date Change'), ('approval_requested', 'Approval Requested'), ('approval_resolved', 'Approval Resolved'), ('time_logged', 'Time Logged'), ('voice_memo', 'Voice Memo'), ('proposal_created', 'Proposal Created'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('proposal_viewed', 'Proposal Viewed'), ('entity_change', 'Field Changed'), ('sms_out', 'SMS (Outbound)'), ('sms_in', 'SMS (Inbound)'), ('whatsapp_out', 'WhatsApp (Outbound)'), ('whatsapp_in', 'WhatsApp (Inbound)'), ('chat', 'Chat Message'), ('meeting_scheduled', 'Meeting Scheduled'), ('call_scheduled', 'Call Scheduled'), ('event_scheduled', 'Event Scheduled'), ('task_expired', 'Task Expired'), ('link', 'Link'), ('payment_received', 'Payment Received'), ('invoice_sent', 'Invoice Sent'), ('signature_requested', 'Signature Requested'), ('signature_completed', 'Signature Completed'), ('ai_summary', 'AI Summary'), ('ai_suggested_action', 'AI Suggested Action'), ('system_note', 'System Note'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('mention', 'Mention'), ('pinned', 'Pinned'), ('unpinned', 'Unpinned')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='streamlineitem',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last resolve action (cleared on reopen).', null=True),
        ),
        migrations.AlterField(
            model_name='streamlineitem',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='The user who last toggled this item to resolved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_streamline_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
