# Generated by Django 6.0.4 on 2026-05-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_task_reopened_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdependency',
            name='type',
            field=models.CharField(choices=[('blocks', 'Blocks'), ('related_to', 'Related To'), ('subtask', 'Subtask')], default='blocks', max_length=20),
        ),
    ]
