# Generated by Django 6.0.4 on 2026-05-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_subtask_dependency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_edited',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
