# Generated by Django 6.0.4 on 2026-05-02 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_activity_edited_at_activity_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company (from the address book) this lead belongs to.', limit_choices_to={'type': 'company'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_leads', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_person',
            field=models.ForeignKey(blank=True, help_text='The specific contact person at the company for this lead.', limit_choices_to={'type': 'person'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_person_leads', to='crm.customer'),
        ),
    ]
