# Generated by Django 6.0.4 on 2026-05-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_soft_delete_priority_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='purge_after',
            field=models.DateTimeField(blank=True, help_text='Scheduled timestamp for hard-delete. Null means never purge automatically.', null=True),
        ),
    ]
