# Generated by Django 6.0.4 on 2026-05-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_savedview_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional hourly rate used for billing calculations.', max_digits=10, null=True),
        ),
    ]
