# Generated by Django 6.0.4 on 2026-05-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_add_hourly_rate_to_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='canonical_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to firm.default_currency at time of last save.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='canonical_currency',
            field=models.CharField(blank=True, help_text='Currency code of canonical_amount.', max_length=3),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='canonical_rate_used',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for canonical_amount calculation.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='canonical_updated_at',
            field=models.DateTimeField(blank=True, help_text='When was canonical_amount last recalculated.', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='canonical_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value converted to firm.default_currency at time of last save.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='canonical_currency',
            field=models.CharField(blank=True, help_text='Currency code of canonical_amount (= firm.default_currency at save time).', max_length=3),
        ),
        migrations.AddField(
            model_name='lead',
            name='canonical_rate_used',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for canonical_amount calculation.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='canonical_updated_at',
            field=models.DateTimeField(blank=True, help_text='When was canonical_amount last recalculated.', null=True),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='canonical_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to firm.default_currency at time of last save.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='canonical_currency',
            field=models.CharField(blank=True, help_text='Currency code of canonical_amount.', max_length=3),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='canonical_rate_used',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for canonical_amount calculation.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='revenueitem',
            name='canonical_updated_at',
            field=models.DateTimeField(blank=True, help_text='When was canonical_amount last recalculated.', null=True),
        ),
    ]
