"""
Django settings for leadlab project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import sentry_sdk

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-k3v5t^24#)=py^go_g3xb(z$mmht_)n+hdbjsh8=11mor_k_f3',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local apps
    'users',
    'firms',
    'crm',
    'frontend',
    'django.contrib.postgres',
    'channels',
    # Brute-force protection (v1.9)
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Axes must come after AuthenticationMiddleware
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'firms.middleware.TenantMiddleware',
    # Content-Security-Policy (v1.9)
    'leadlab.middleware.ContentSecurityPolicyMiddleware',
]

ROOT_URLCONF = 'leadlab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'leadlab.wsgi.application'
ASGI_APPLICATION = 'leadlab.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', ''),
    }
}

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Redis / Celery
_REDIS_URL_OVERRIDE = os.environ.get('REDIS_URL', '')
REDIS_URL = _REDIS_URL_OVERRIDE or 'redis://localhost:6379/0'
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# Celery Beat — periodic tasks
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'weekly-pipeline-digest': {
        'task': 'crm.tasks.send_weekly_digest',
        # Every Monday at 08:00 UTC
        'schedule': crontab(hour=8, minute=0, day_of_week=1),
    },
    'email-sequences-dispatch': {
        'task': 'crm.tasks.dispatch_sequence_emails',
        # Every 15 minutes
        'schedule': crontab(minute='*/15'),
    },
    # v2.5 — Workflow Automation periodic checks
    'automation-task-overdue': {
        'task': 'crm.tasks.check_task_overdue_automations',
        # Once per day at 09:00 UTC
        'schedule': crontab(hour=9, minute=0),
    },
    'automation-record-inactivity': {
        'task': 'crm.tasks.check_record_inactivity_automations',
        # Once per day at 10:00 UTC
        'schedule': crontab(hour=10, minute=0),
    },
    # Phase 7 — Spawn recurring task instances once per day at midnight UTC
    'spawn-recurring-tasks': {
        'task': 'crm.tasks.spawn_recurring_tasks',
        'schedule': crontab(hour=0, minute=5),
    },
    # Calendar / Task unification — auto-close scheduled tasks past their grace
    'auto-expire-scheduled-tasks': {
        'task': 'crm.tasks.auto_expire_scheduled_tasks',
        'schedule': crontab(minute='*/15'),
    },
    # Safe-remove — hard-delete records whose purge_after has elapsed
    'purge-soft-deleted-records': {
        'task': 'crm.tasks.purge_soft_deleted_records',
        'schedule': crontab(hour=3, minute=0),
    },
    # Exchange Rate Engine — fetch ECB daily rates (ECB publishes by ~16:00 CET)
    'fetch-ecb-exchange-rates': {
        'task': 'crm.tasks.fetch_ecb_exchange_rates',
        'schedule': crontab(hour=17, minute=30),
    },
}

# Safe-remove: number of days before a soft-deleted record is hard-deleted.
SOFT_DELETE_PURGE_DAYS = int(os.environ.get("SOFT_DELETE_PURGE_DAYS", "30"))

# Stripe
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_PRICE_ID = os.environ.get('STRIPE_PRICE_ID', '')

# Email (SMTP)
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@leadlab.io')

# Media / Storage
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# AWS S3 (optional)
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'eu-central-1')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Cache (Redis when REDIS_URL env var is explicitly set; LocMemCache otherwise)
# ---------------------------------------------------------------------------

CACHES = {
    'default': (
        {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
        if _REDIS_URL_OVERRIDE
        else {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    )
}

# ---------------------------------------------------------------------------
# Rate limiting
# ---------------------------------------------------------------------------

# Set to False to disable rate limiting globally (e.g. in tests).
RATELIMIT_ENABLE = os.environ.get('RATELIMIT_ENABLE', 'True') == 'True'

# ---------------------------------------------------------------------------
# Sentry — error tracking (optional; only initialised when SENTRY_DSN is set)
# ---------------------------------------------------------------------------

_SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if _SENTRY_DSN:
    sentry_sdk.init(
        dsn=_SENTRY_DSN,
        send_default_pii=False,
    )

# ---------------------------------------------------------------------------
# Django Channels — channel layer (Redis when REDIS_URL is set, in-memory otherwise)
# ---------------------------------------------------------------------------

if _REDIS_URL_OVERRIDE:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }

# ---------------------------------------------------------------------------
# django-axes — brute-force protection (v1.9)
# ---------------------------------------------------------------------------

AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend must be first
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_FAILURE_LIMIT = int(os.environ.get('AXES_FAILURE_LIMIT', '10'))
AXES_COOLOFF_TIME = 1  # hours
AXES_LOCKOUT_PARAMETERS = ['ip_address', 'username']
# Disable axes in testing to avoid interference. AxesBackend rejects
# `client.login(username=..., password=...)` calls (which don't pass a request),
# so we auto-disable when running under the Django test runner.
import sys as _sys
_running_tests = (
    'test' in _sys.argv
    or any('pytest' in str(arg) for arg in _sys.argv)
)
AXES_ENABLED = (
    not _running_tests
    and os.environ.get('AXES_ENABLE', 'True') == 'True'
)

# ---------------------------------------------------------------------------
# Web Push (VAPID) settings (v1.9)
# ---------------------------------------------------------------------------

VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY', '')
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '')
VAPID_ADMIN_EMAIL = os.environ.get('VAPID_ADMIN_EMAIL', 'admin@leadlab.io')

# ---------------------------------------------------------------------------
# Content-Security-Policy (v1.9)
# ---------------------------------------------------------------------------

# The CSP is enforced via leadlab.middleware.ContentSecurityPolicyMiddleware.
# Override individual directives via environment variables.
CSP_DEFAULT_SRC = os.environ.get("CSP_DEFAULT_SRC", "'self'")
CSP_SCRIPT_SRC = os.environ.get(
    "CSP_SCRIPT_SRC",
    "'self' 'unsafe-inline' https://cdn.jsdelivr.net",
)
CSP_STYLE_SRC = os.environ.get(
    "CSP_STYLE_SRC",
    "'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net",
)
CSP_FONT_SRC = os.environ.get("CSP_FONT_SRC", "'self' https://fonts.gstatic.com")
CSP_IMG_SRC = os.environ.get("CSP_IMG_SRC", "'self' data: blob:")
CSP_CONNECT_SRC = os.environ.get("CSP_CONNECT_SRC", "'self' wss: ws:")
CSP_WORKER_SRC = os.environ.get("CSP_WORKER_SRC", "'self' blob:")
CSP_MEDIA_SRC = os.environ.get("CSP_MEDIA_SRC", "'self' blob:")
CSP_REPORT_URI = os.environ.get("CSP_REPORT_URI", "")

# ---------------------------------------------------------------------------
# First-party plugins (v2.4)
# Plugins self-register by importing their module.  Only import here so that
# plugin registration happens after all Django apps are fully loaded.
# ---------------------------------------------------------------------------

def _load_builtin_plugins():
    """Import all first-party plugin modules so they call register()."""
    import importlib
    _BUILTIN_PLUGINS = [
        "plugins.slack_notifications",
        "plugins.linkedin_enrichment",
        "plugins.voip",
        "plugins.email_sequences",
        "plugins.fakturoid",
    ]
    for module_path in _BUILTIN_PLUGINS:
        try:
            importlib.import_module(module_path)
        except Exception as exc:  # noqa: BLE001
            import logging
            logging.getLogger(__name__).warning(
                "Failed to load built-in plugin %s: %s", module_path, exc
            )


_load_builtin_plugins()
